### PR TITLE
Tiny fixes/improvements for de_DE.lang

### PR DESCRIPTION
**Pull request by Vexatos**
Just some small fixes.

### CODE REVIEW

**Comment by bendem** [comment]
You should maybe read [this file](https://github.com/Kobata/inventory-tweaks/blob/develop/src/minecraft/assets/inventorytweaks/lang/_README.txt) which is call read me ;-)

**Comment by Vexatos** [comment]
Oops, sorry.
But that means I have to sign up to this website I don't know :|

**Comment by bendem** [comment]
If you want to contribute to the translation, i think you have to do it that way.

**Comment by Vexatos** [comment]
Okay, I will look over that :|

**Comment by Vexatos** [comment]
Okay, I looked over the translations there and added comments here and there. I hope more people will look at it and vote. Most translations are good, there were only grammar and punctuation mistakes (In the German language there are a lot of hyphens and commas, a lot more than in the English language).

**Pull request closed without merging**
