### PR TITLE
[MC 1.14] MCP remappings

### PR DESCRIPTION
**Pull request by jadar**
### Overview

Merge #592 first. 

Following the [suggestions](https://gist.github.com/williewillus/353c872bcf1a6ace9921189f6100d09a) for updating to 1.13/1.14, this PR applies some mappings to transition from 1.12 to 1.14. Obviously still doesn't build, but it's a start. 

### Changes
- Ran mappings from 1.12 to 1.13 from [here](https://github.com/ModCoderPack/MCPBot-Issues/tree/master/migrations).
- Ran mappings from 1.13 to 1.14 from [here](https://gist.github.com/williewillus/2dfc945b7b7fdb69cc3ff830072d22fe).

### CODE REVIEW

**Comment by Kobata** [comment]
It's a bit confused by the duplicate commit I think.

**Comment by Kobata** [comment]
I guess the PR view just isn't showing that the first commit was already applied so eh. Github's weird like that.

**Comment by jadar** [comment]
Hah. I do that with Bitbucket all the time and it seems to work. Thanks!

**Comment by BenjaminHoegh** [comment]
just a question, is this something there is still being developed or are this mod dead?

**Pull request merged**
