### PR TITLE
Hide Config Loaded Chat message & Fix Travis Builds

### PR DESCRIPTION
**Pull request by HeroCC**
Hi Kobata!
This PR is a request from me, and [several](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288184-inventory-tweaks-1-59-march-31?comment=1654) [other](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288184-inventory-tweaks-1-59-march-31?comment=1615) [people](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288184-inventory-tweaks-1-59-march-31?comment=1605) alike me that don't like the startup message that InvTweaks prints. This PR makes it log the same message (Couldn't get translation to work though) to the console, instead of the chat log. I hope you will merge this, it will make it much less annoying for many people. 
Thanks!

### CODE REVIEW

**Comment by HeroCC** [comment]
I meant to make another PR, but I just made a quick change to fix Travis Builds: it was looking for an API key, but we don't want to submit to Curse for PRs and stuff, so just build

**Comment by Kobata** [comment]
1a10a8f6192b8f66ed3a4fb723ba23134d691b99 added an option to just disable them -- it's a nice message in some situations (to let you know it did find and load your changes successfully)

As for travis, I'll have to ask abrar -- it does need to run the curse task to upload for main builds

**Comment by Kobata** [comment]
I think I have a better solution for both of these, but I need to get a check on the travis fix that it won't cause some strange issue later.

**Comment by HeroCC** [comment]
OK, thanks for the feature, and good luck with travis!

**Pull request closed without merging**
