### PR TITLE
Tooltip of item tree path.

### PR DESCRIPTION
**Pull request by IMarvinTPA**
I think I have the git thing somewhat sussed.

### CODE REVIEW

**Comment by Kobata** [comment]
Assuming it's still fairly easy to do so, it might be a good idea to set the color on these to grey, like the vanilla ID tooltips that show up.

In fact if the expected usecase for this is fairly limited, it might be worth leaving the toggle as config-file only and/or considering also limiting it to only when advanced tooltops are on.

**Comment by IMarvinTPA** [comment]
Color is easy.  I was on the fence about adding the button to either config screen at all too.  Maybe the advanced one?

**Comment by Kobata** [comment]
So, the big question is who do you think would use it:

If it's mostly just for people working on the mod/integrations with it, then it might as well be a config-only thing since you'll need some setup there anyway.

If it's for people making modpacks to configured, they're already messing with most of the config files but maybe a button in advanced would help discoverability.

I can't see much reason for actual players to ever have this setting on, which means it probably shouldn't be a setting you find immediately when looking to see what is possible.

**Comment by IMarvinTPA** [comment]
If you have JEI set to search using tool-tips, it allows the words used in the tree to find items.  Such as if farming would bring up farming related machines in my big tree (and hoes and agricraft stuff.)  It does seem to require a restart as the tool-tip indexing is done at loading.

**Pull request merged**
