### PR TITLE
Better Name sorting for things like bees and Roost chicken.

### PR DESCRIPTION
**Pull request by IMarvinTPA**
Improve the sorting for overloaded items with different names.

(I haven't figured out how to make the previous pull request files not participate in this one.)

### CODE REVIEW

**Comment by Kobata** [comment]
> (I haven't figured out how to make the previous pull request files not participate in this one.)

You need to rebase things on master and delete the extra commits since I have github set to squash things instead of use merge commits.

**Comment by IMarvinTPA** [comment]
It is a small change, would you mind just changing it without using the pull request?

**Comment by Kobata** [comment]
Because of how it works I can just press the button and fix the names.

For future stuff it probably makes it easier to just use a new branch for each pr based directly on this repo's, that way there's less extra stuff that can get in.

**Comment by IMarvinTPA** [comment]
Agreed.  I'm still trying to get the hang of git.

**Comment by IMarvinTPA** [comment]
So, this improvement caused the comparator to break the comparator contract.  I know how to fix it though.  (The item == item comparison has to go.)

**Comment by Kobata** [comment]
See #397, there's probably been various things in there that have strictly broken the method's use as a standard Java comparator for some time in certain circumstances.

**Comment by IMarvinTPA** [comment]
The function "TheHuntForTheOffendingItems" in https://github.com/mezz/JustEnoughItems/pull/1383/commits/7d6f1062a49e477f72e736c761e287f5861f529f is how I have figured out how to find the items that expose the misbehavior.  I just don't know how I want to go about getting the comparator compliant push to you.  (Different fork from the tooltip, wait for that one to be cleared, or just do both together.)
Another symptom of breaking the contract is when items will shift around each time you click the sort button.

**Comment by Kobata** [comment]
Easiest way is just to make a separate branch unless you really want to wait on it.

**Pull request merged**
