### PR TITLE
Fix #386 Sort buttons can't be clicked when they overlap JEI

### LINKED ISSUE #386: Sort buttons can't be clicked when they overlap JEI
**Minecraft Version:** 1.10.2
**Inventory Tweaks Version:** 1.61-58
- Set GUI scale to auto.
- Open an iron chest or other large inventory.
- The sort buttons on the top-right overlap with JEI.
- The sort buttons can't be clicked, instead you're selecting items in JEI.

The sort button tool tips appear. But you can't seem to click them.
Tested with ironchest-1.10.2-7.0.9.796 and jei_1.10.2-3.9.0.244.

### PR DESCRIPTION
**Pull request by mezz**
Fixes #386 
Rewritten version of #398
Does not have a compile-time dependency on JEI. Moves the buttons like it does for NEI.

### CODE REVIEW

**Comment by Kobata** [comment]
This is more of what I was looking for, thanks :)

Just waiting on travis to finish, it seems to have gone all weird and started 3 builds?

**Comment by mezz** [comment]
I pushed some formatting fixes a couple times, travis probably picked up each one.

**Comment by Kobata** [comment]
That makes sense, I suppose. They did seem to be mostly the same just with different commit IDs.

I'll probably end up just running an IDE-reformat at some point anyway.

**Comment by mezz** [comment]
It looks like this isn't working in 1.11, probably because the ModIDs are all lowercase now.
Edit: people are reporting it doesn't work in 1.10 either.

**Comment by Kobata** [comment]
Yeah I guess that'd probably break it.

As for 1.10, this didn't get into a release version, it's the next -dev *right after* the 1.10 release. (Although before the branch switched to 1.11)

**Comment by Kobata** [comment]
That should fix the modids for 1.11: Apparently the current one for NEI is 'nei' and not 'notenoughitems'

**Comment by mezz** [comment]
Ah that makes more sense now, ok.
Thanks for the quick fix.

**Pull request merged**
