### PR TITLE
Update for latest Forge

### PR DESCRIPTION
**Pull request by TehNut**
- Made use of Forge's new registry system 
  - `Item.itemRegistry.getNameForObject(ITEM)` -> `ITEM.getRegistryName().toString()`
  - `Item.itemRegistry.getObject(RESOURCELOCATION)` -> `ForgeRegistries.ITEMS.getValue(RESOURCELOCATION)`
- Noticed an NPE when refilling the held slot so I added a null-check there.

Also updated mappings to go along with it.

### CODE REVIEW

**Comment by TehNut** [comment]
I forgot to set the [required Forge version](https://github.com/Inventory-Tweaks/inventory-tweaks/blob/develop/src/main/java/invtweaks/forge/InvTweaksMod.java#L21) to at least `12.16.0.1863`. Should I do that?

**Comment by TehNut** [comment]
@Kobata Since there is an RB of Forge for 1.9, could this possibly get merged?

**Comment by MazeusXenon** [comment]
Just wondering if this is actually released in the alpha for 1.9 on May 1. Yes, I know this isn't closed, but I ask as I see that there has been changes and a commit from this ticket, but I get the exact same error when I load both InvTweaks and TechReborn as with the [original error submitted](https://github.com/TechReborn/TechReborn/issues/553). I am on the most recent release version of Forge, and even tried the latest version of Forge, and neither play nice and so boom when I load the client.

The original error was is also here: http://pastebin.com/U3mHZgSa

Thanks! I love this mod and wish I knew Java so I could help...

**Comment by TehNut** [comment]
This has not been fixed. You can find a temporary fixed version [here](https://github.com/TehNut/inventory-tweaks/releases/tag/1.61-1.9Fix).

**Comment by MazeusXenon** [comment]
Cool - thanks. And yes, I understand this is an Alpha (at best) so if other things go whackadoodle, I'll let you know or just deal with it! :)

**Pull request closed without merging**
